site_name: <b><font style="Times New Roman">Predicting Broker Performance for 2019</font></b>
nav:
    - Home: 'index.md'
    - Data Analysis: 'EDA.md'
    - Clustering & PCA: 'Clustering.md'
    - Modelling: 'Prediction.md'
    - Results: 'Results.md'
    

